### ISSUE TITLE
Availability of Model Weights/Pretrained Models

### ISSUE THREAD

**Issue by schengal4** [ecg-net/PreOpNet#2]
I appreciate your use of ML techniques to predict perioperative risk outcomes, with the potential to help physicians identify at-risk patients and provide the appropriate interventions. 

I'm just wondering about whether the model weights are available as training the models from scratch is too computationally intensive for my use case. If they're not available due to patient privacy or other reasons, I totally understand. :)

**Comment by echonet** [comment]
The model weights are in the repo. Check the .pt checkpoint files.

**Comment by schengal4** [comment]
Thank you for letting me know. Happy New Year! :)
